# Generated by Django 2.2 on 2020-04-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('iphone', 'iphone'), ('Redmi', 'Redmi'), ('Samsung', 'Samsung')], default='', max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('specifications', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
