# Generated by Django 2.2 on 2020-04-19 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200417_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='final_price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='phone',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='sale_price',
            field=models.CharField(default='10', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
