from django.urls import path
from.import views
urlpatterns = [
     path('',views.index,name="index"),
     path('mobile/',views.mobile,name="mobile"),
     path('redmi/',views.redmi,name="redmi"),
     path('samsung/',views.samsung,name="samsung"),
     path('iphone/',views.iphone,name="iphone"),
     path('sale/',views.sale,name="sale"),
     path('signup/',views.signup,name="signup"),
     path('login/',views.login,name="login"),
     path('signup_user/',views.signup_user,name="signup_user"),
     path('verify_user/',views.verify_user,name="verify_user"),
     path('login_user/',views.login_user,name="login_user"),
     path('logout/',views.logout,name="logout"),
     path('detail/<int:pk>/',views.detail,name="detail"),
     path('feedback/<int:pk1>/<int:pk2>/',views.feedback,name="feedback"),
     path('submit_feedback/<int:pk1>/<int:pk2>/',views.submit_feedback,name="submit_feedback"),
     path('add_to_cart/<int:pk1>/<int:pk2>/',views.add_to_cart,name="add_to_cart"),
     path('mycart/',views.mycart,name="mycart"),
     path('remove_cart/<int:pk>/',views.remove_cart,name="remove_cart"),
     path('change_password/',views.change_password,name="change_password"),
     path('verify_pass_otp/',views.verify_pass_otp,name="verify_pass_otp"),
     path('password_form/',views.password_form,name="password_form"),
     path('forgot_password/',views.forgot_password,name="forgot_password"),
     path('verify_forgot_password/',views.verify_forgot_password,name="verify_forgot_password"),
     path('verify_otp_forgotpassword/',views.verify_otp_forgotpassword,name="verify_otp_forgotpassword"),
     path('confirm_password_form/',views.confirm_password_form,name="confirm_password_form"),
     path('payment/', views.payment, name="payment"),
     path('myorder/', views.myorder, name="myorder"),
]